Extend datamap logic with alternative worksheet implementation
nfdi4plants/ARC-specfication pull request #113
Opened 2024-07-08 07:38 UTC by Freymaurer

Following the current ARC-specification each Assay/Study can be related to at most **one** `isa.datamap.xlsx` file. And each `isa.datamap.xlsx` fiel MUST contain at most most **one** `isa_datamap` worksheet, which MUST contain at most **one** table named `datamapTable`.

This allows us to give an alternative implementation as additional named worksheet directly in assay/study. Allowing this structure would make development for Swate easier, as well as maintaining familiar behavior of downloading only one file.

Should one assay have a `isa_datamap` sheet with a `datamapTable`, as well as a `isa.datamap.xlsx` at the correct position, the question arises how to handle this "double information. In my opinion there are several options on how to handle this:

1. Extend `isa.datamap.xlsx` information with sheet (KEEP BOTH)
2. Prioritize `isa.datamap.xlsx`
3. Prioritize sheet

The current PR defines variant 3. I think, that this is the least "magic" by also choosing "specific" over "general".

Let me know what you think @HLWeil @kappe-c @floWetzels @ZimmerD @kMutagene @chgarth @muehlhaus @gdoniparthi

2024-07-08 14:04 UTC, HLWeil requested changes
Seems like a sensible thing to do.

Two things though:

1. Could you remote the `Datamap Sheet` section you added and instead mention in the `Assay file` and `Study file` sections?
2. Could you also add a small mention with basically the same information in the [Study](https://github.com/nfdi4plants/ARC-specification/blob/main/ARC%20specification.md#study-and-resources) and [Assay](https://github.com/nfdi4plants/ARC-specification/blob/main/ARC%20specification.md#assay-data-and-metadata) sections of the main ARC-specification file? Best place would be the paragraphs where there's talk about the datamap file.

2024-07-08 20:04 UTC, Freymaurer commented
I started working on your request, but noticed that this would require a lot of information duplication. Stating the same information at multiple points in the specification. Therefore i propose another solution.

- I added references to the ARC-specification
- In ISA-XLSX specification i added references in study and assay to datamap sheet.
- Both datamap file and datamap sheet do now crossreference to datamap table which contains specific column information

2024-07-15 11:35 UTC, HLWeil requested changes
I see the problem of duplication, but now some inconsistencies were introduced into the isa-xlsx specification. Especially splitting the `datamap table sheet` into a `table` and `sheet` section. This is inconsistent with the `annotation table sheet` and `top level metadata sheet` sections. 

Therefore I propose to undo this split, mention the possibility to have the  `datamap table sheet` directly in the assay or study file (as you did) and be a little bit more specific in the assay and study sections of the arc-specification.

2024-07-15 11:35 UTC, HLWeil commented on ISA-XLSX.md
> +## Datamap Sheet
Remove this section

2024-07-15 11:35 UTC, HLWeil commented on ISA-XLSX.md
> +Any Study MAY contain datamap references as described in the [`Datamap Sheet`](#datamap-sheet) section.
Keep this

2024-07-15 11:35 UTC, HLWeil commented on ISA-XLSX.md
> +Any Assay MAY contain datamap references as described in the [`Datamap Sheet`](#datamap-sheet) section.
Keep this

2024-07-15 11:35 UTC, HLWeil commented on ISA-XLSX.md
> -The `Datamap File` MUST contain one [`Datamap table sheet`](#datamap-table-sheets). This sheet MUST be named `isa_datamap`.
Undo

2024-07-15 11:35 UTC, HLWeil commented on ISA-XLSX.md
> -# Datamap Table sheets
Undo

2024-07-15 11:35 UTC, HLWeil commented on ISA-XLSX.md
> -`Datamap Table sheets` are used to describe the contents of data files.
Undo

2024-07-15 11:35 UTC, HLWeil commented on ISA-XLSX.md
> -In the `Datamap Table sheets`, column headers MUST have the first letter of each word in upper case, with the exception of the referencing label (REF).
Undo

2024-07-15 11:35 UTC, HLWeil commented on ISA-XLSX.md
> -`Datamap Table sheets` are structured with fields organized on a per-row basis. The first row MUST be used for column headers. Each body row is an implementation of a `data` node.
Undo

2024-07-15 11:35 UTC, HLWeil commented on ISA-XLSX.md
> -Every `Datamap Table sheet` MUST contain a `Data` column. Every  object in this column MUST correspond to a relevant data resource location, following the [Data Path Annotation](/ARC%20specification.
Undo

2024-07-15 11:35 UTC, HLWeil commented on ARC specification.md
> +- *Studies* are collections of material and resources used within the investigation. Study-level metadata is stored in [ISA-XLSX](#isa-xlsx-format) format in a `isa.study.xlsx` file, which MUST exist
format in a `isa.datamap.xlsx` file **in the study folder** or `isa_datamap` worksheet in the **isa.study.xlsx** file

2024-07-15 11:35 UTC, HLWeil commented on ARC specification.md
> +- *Assays* correspond to outcomes of experimental assays or analytical measurements (in the interpretation of the ISA model) and are treated as immutable data. Each assay is a collection of files, to
format in a `isa.datamap.xlsx` file **in the assay folder** or `isa_datamap` worksheet in the **isa.assay.xlsx** file

2024-07-15 11:35 UTC, HLWeil commented on ISA-XLSX.md
> +- [Datamap Table](#datamap-table)
Undo

2024-07-15 12:27 UTC, Freymaurer commented
Done! Have a look!

2024-07-15 18:51 UTC, HLWeil approved these changes
Thanks for the adjustments. Just saw that the links need to be fixed. Else it's ready to go.

2024-07-15 18:51 UTC, HLWeil commented on ISA-XLSX.md
> +Any Study MAY contain datamap references as described in the [`Datamap Sheet`](#datamap-sheet) section.
The links need to be fixed (#datamap-table-sheet)

2024-07-15 18:51 UTC, HLWeil commented on ISA-XLSX.md
> +Any Assay MAY contain datamap references as described in the [`Datamap Sheet`](#datamap-sheet) section.
The links need to be fixed (#datamap-table-sheet)

2024-07-15 19:11 UTC, Freymaurer commented
@HLWeil fixed! 👍

2024-07-15 19:28 UTC, merged