Overhaul Ontology Annotations
nfdi4plants/ARC-specfication pull request #120
Opened 2024-09-06 13:50 UTC by HLWeil

I overhauled the specificiation of Ontology Annotations in Annotation tables. Now the specification tries to be more specific about when it talks about the `header cells` or the `value cells`. Previously, this was very confusing (see #115) or even ambiguous. 

Please @UrsulaE, @StellaEggels, @Hannah-Doerpholz, @Freymaurer take a look regarding correctness of terminology and also clarity of formulation. 

As usual, @Brilator @muehlhaus @chgarth 

closes #114 in short fix
closes #115

2024-09-09 08:19 UTC, Brilator commented on ISA-XLSX.md
> +The value in the `Term Source REF` column MUST either contain a short identifier for the `IDSPACE`, which identifies the ontology the term can be found in, or be left empty.
maybe easier: "the ontology containing the term"

2024-09-09 08:21 UTC, StellaEggels commented
Two small things I would change:
1. It says to use <IDSPACE>:<LOCALID> , but in the examples sometimes <IDSPACE> and <LOCALID> are separated by ":" and sometimes by "_". I would always use ":".
2. For Parameters, the example is "time" with Kelvin as a unit, so either change the parameter to temperature or change the unit.

2024-09-09 08:24 UTC, StellaEggels commented
regarding 1.: I meant between ID SPACE and LOCAL ID (the words I copied didn't show...)

2024-09-09 08:42 UTC, Hannah-Doerpholz commented
It might be good to also add that in case of columns with units, that the "main" term column is not immediately followed by the `Term Source REF` and `Term Accession Number` columns. Maybe just with a pointer that this is described in the next section. Maybe like this (line 695):
Where a value is an `Ontology Annotation` in an annotation table, `Term Accession Number` and `Term Source REF` columns MUST follow the main column, unless the main column contains a unit. In that case refer to the next section.

2024-09-09 11:16 UTC, HLWeil commented
> Two small things I would change:
> 
> 1. It says to use : , but in the examples sometimes  and  are separated by ":" and sometimes by "_". I would always use ":".
> 2. For Parameters, the example is "time" with Kelvin as a unit, so either change the parameter to temperature or change the unit.

-"When will the world end"
-"I don't know exactly, but it will probably end in 10000 Kelvin"

2024-09-09 11:33 UTC, HLWeil commented
Thanks a lot for your inputs, @Brilator @StellaEggels @Hannah-Doerpholz!

Could you take another look whether your remarks where incorporated as intended?

2024-09-11 09:46 UTC, Freymaurer requested changes

2024-09-11 09:46 UTC, Freymaurer commented on ISA-XLSX.md
> +The headers of the two annotation columns SHOULD contain further ontological information about the ontology term of the main header. In this case, following the static header string, separated by a s
What if the header term is freetext? You are using MUST here? what is the alternative?

2024-09-11 09:46 UTC, Freymaurer commented on ISA-XLSX.md
> +  - `LOCALID` of the ontology, which is only applicable if the matching `IDSPACE` is given in the `Term Source REF` column
`LOCALID` => do we support this in ARCtrl?

2024-09-11 09:46 UTC, Freymaurer commented on ISA-XLSX.md
> +> Note: In this example, the value in the `Term Accession Number` column is formatted as a `URL`, but shortened for the purpose of markdown-formatting.
> [!NOTE]
> Github has a very nice markdown feature for notes 🙂

2024-09-11 11:08 UTC, HLWeil commented on ISA-XLSX.md
> +The headers of the two annotation columns SHOULD contain further ontological information about the ontology term of the main header. In this case, following the static header string, separated by a s
Then it's not an ontology term and none of this applies 😅

2024-09-11 11:14 UTC, HLWeil commented on ISA-XLSX.md
> +  - `LOCALID` of the ontology, which is only applicable if the matching `IDSPACE` is given in the `Term Source REF` column
Nope, will open an Issue

2024-09-11 11:23 UTC, HLWeil commented on ISA-XLSX.md
> +> Note: In this example, the value in the `Term Accession Number` column is formatted as a `URL`, but shortened for the purpose of markdown-formatting.
I feel like this deserves its own Issue as a discussion. OFc they look nice in GitHub but weird when not formatted in other Markdown editors.

Also there's a full spectrum of [alerts](https://docs.github.com/de/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) than can be used. But we should use them unified across the specs.

2024-09-11 13:11 UTC, HLWeil commented on ISA-XLSX.md
> +> Note: In this example, the value in the `Term Accession Number` column is formatted as a `URL`, but shortened for the purpose of markdown-formatting.
Okay will implement it here in the isa-xlsx specs. But we still need some unification of the work `Notes` in the main specification file. As it's used there for actual notes but also for the specification itself.

2024-09-11 13:16 UTC, HLWeil commented on ISA-XLSX.md
> +> Note: In this example, the value in the `Term Accession Number` column is formatted as a `URL`, but shortened for the purpose of markdown-formatting.
Okay made the change. Not sure whether the side-notes are now too attention-grabbing though 😅

2024-09-11 13:24 UTC, Freymaurer approved these changes

2024-09-11 13:25 UTC, merged

2025-02-28 13:24 UTC, kMutagene commented on ISA-XLSX.md
> +  - `LOCALID` of the ontology, which is only applicable if the matching `IDSPACE` is given in the `Term Source REF` column
@HLWeil bump, does this issue exist?